### ISSUE TITLE
Реализация метода отправки уведомлений через бота телеграмма

### ISSUE THREAD

**Issue by gil9red** [MeowNya/Gold_apple_scripts#2]
- [x] Предлагаю завести отдельный скрипт py в нем функцию для отправки сообщений боту.
    Примеры
    * Подключение к телеграмму:
        https://github.com/gil9red/telegram_notifications_bot/blob/d837cde5fdfa25b6f7f753dc52aef4e75e49d429/main.py#L118-L126
    
        Для отправки это не понадобится:
        ```
        updater.start_polling()
        updater.idle()
        ````

    * Отправка через бота:
        https://github.com/gil9red/telegram_notifications_bot/blob/d837cde5fdfa25b6f7f753dc52aef4e75e49d429/main.py#L52
- [x] Для отправки достаточно иметь chat_id, для приватного чата с ботом, это текущий id пользователя
        [Пример того как узнать свой user_id и chat_id](https://github.com/gil9red/SimplePyScripts/blob/7da7f202be04dfc2e1124c6fa0e0f7bf1b021904/telegram_bot_examples/get_user_info.py#L29)
        Еще я могу тебе его сказать, посмотрев по логам своих ботов, если ты отправишь им сообщение
- [x] Бота создать

**Comment by MeowNya** [comment]
7b0974cc488488af5e7e58c59816ed06c649df46
