### ISSUE TITLE
В цикл добавить отлов ошибок для увеличения надежности скрипта

### ISSUE THREAD

**Issue by gil9red** [MeowNya/Gold_apple_scripts#3]
- [x] Предлагаю в цикл добавить `try` / `except` и ловить `Exception`
- [x] Если ошибка произошла, то вывести ее в консоль (используй модуль `traceback`) в `print`
- [x] Добавить задержку между повторением кода в `except`

**Comment by MeowNya** [comment]
5af468547577e3829b6ae74923662cc8d35f2c85
