### ISSUE TITLE
Добавить логирование работы парсера в файл

### ISSUE THREAD

**Issue by gil9red** [MeowNya/Gold_apple_scripts#4]
- [x] Использовать модуль `logger` ([пример](https://github.com/gil9red/telegram__farguscovers_bot/blob/48cd78b86cfc65d39a22d0b5cd5b95aa50cc688d/bot/common.py#L23))
- [x] Логировать одинаково в stdout и в файл
- [x] Для логирования исключений не нужно использовать `traceback`, вместо этого использовать `log.exception`, которое само берет трассу стека ошибка и добавляет ее в лог

**Comment by MeowNya** [comment]
e33cba69b0c86116e90a89dcb26b88a41248229e
