### ISSUE TITLE
Помнить последнее значение парсера

### ISSUE THREAD

**Issue by gil9red** [MeowNya/Gold_apple_scripts#5]
- [x] Завести файл, в котором будет храниться последнее значение парсера - `prev_val`
- [x] При запуске скрипта заполнять из файла в переменную `prev_val`
    - [x] На первый запуск, когда `prev_val = None`, сразу же сохранить в файл
- [x] При изменении значения `prev_val` сразу же записывать в файл

**Comment by MeowNya** [comment]
0215966c93a1c1f3458e9e13419f6c7cd0329b42
