### ISSUE TITLE
Отправка сообщения о ошибке в телеграм, если она подряд повторяется n-раз

### ISSUE THREAD

**Issue by gil9red** [MeowNya/Gold_apple_scripts#6]
- [x] Использовать механизм отправки уведомлений из https://github.com/MeowNya/Gold_apple_scripts/issues/2
- [x] Ввести количество повторов, это то, сколько раз можно попробовать парсить сайт перед тем как в телеграм отправить ошибку
- [x] Добавить в начало сообщения-ошибки какое-нибудь эмодзи, типа "внимание"

**Comment by MeowNya** [comment]
43c6ede3e79ea83230b59de5c83dcb746f5669a8
