### ISSUE TITLE
Исправление ошибки. Уведомление о изменении никогда не сработает

### ISSUE THREAD

**Issue by gil9red** [MeowNya/Gold_apple_scripts#7]
Условие всегда будет `False`, т.к. `prev_val` всегда при запуске `None`:

https://github.com/MeowNya/Gold_apple_scripts/blob/f6ec1c6175b6f03d0266e8c26bd7f7396f454e17/main.py#L26

- [x] Решением будет дополнительная проверка на `None` (типа на первый запуск) и актуализация значения
- [x] Чтобы не было пропуска первой проверки, нужно сделать доработку https://github.com/MeowNya/Gold_apple_scripts/issues/5

**Comment by MeowNya** [comment]
0215966c93a1c1f3458e9e13419f6c7cd0329b42
